### PR TITLE
HAOS 2023.4

### PR DESCRIPTION
**Pull request by GuGu927**
I edited some code that is causing errors in the latest version of Home Assistant Operating System.
Updated version number to  0.3 and add hacs.json file.

ps.
Is it possible to add the keepAlivePeriod option to the MQTT settings in the gateway firmware?

### CODE REVIEW

**Comment by volca** [comment]
Thanks for your PR. We'll review it soon.

**Comment by volca** [comment]
> ps.
> Is it possible to add the keepAlivePeriod option to the MQTT settings in the gateway firmware?

It's possible. What's your requirement about this?

**Comment by GuGu927** [comment]
@volca I'm using HomeAssistant Addon MQTT Broker.
MQTT broker addon with version 6.2.0, it need keepAlivePeriod parameter when connect to broker.
if not provide keepAlivePeriod parameter, it throws error like this.
**error: received null username, clientid or topic, or access is equal or less than 0 for acl check**

So, I hope keepAlivePeriod option in GatewayConfigTool.
then gateway will connect to broker with parameter.

**Comment by volca** [comment]
ok. We'll update the firmware soon. What firmware version is your gateway?

**Comment by GuGu927** [comment]
> ok. We'll update the firmware soon. What firmware version is your gateway?

I'm using AB BLE Gateway V4.
Firmware Version is 1.5.12
Hardware Version is 4.0

**Comment by volca** [comment]
The firmware is ready. But you need run the config tool from [the source code](https://github.com/AprilBrother/gw4-config-tool). Can you get the config tool work form source code?

**Comment by GuGu927** [comment]
> The firmware is ready. But you need run the config tool from [the source code](https://github.com/AprilBrother/gw4-config-tool). Can you get the config tool work form source code?

Wow. So fast!
Unfortunately I can't get config tool from source code.
I'll just wait for new version :)

**Comment by volca** [comment]
Our config tool for Android is ready. Please try [the package](https://i1.aprbrother.com/apk/gw-config-tool-v1.0.9.apk) if you have android phone.

**Pull request merged**
